datasources:
    default:
        db-type: mysql
        dialect: MYSQL
        driver-class-name: com.mysql.cj.jdbc.Driver
endpoints:
    flyway:
        enabled: true
        sensitive: false
flyway:
    datasources:
        default:
            enabled: true
micronaut:
    application:
        name: micronautguide
