micronaut:
    application:
        name: tacoCloud
    router:
        static-resources:
            css:
                mapping: /css/*.css
                paths: classpath:static/css
            images:
                mapping: /images/**
                paths: classpath:static/images
    session:
        http: true

datasources:
    default:
        dialect: H2
        driver-class-name: org.h2.Driver
        url: jdbc:h2:file:/Users/yunwu/IdeaProjects/SpringInAction/micronaut/ch3/TacoCloud/src/main/resources/data/tacocloud;AUTO_SERVER=true
        username: sa
        password: ""

jpa:
    default:
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
                show_sql: true

#flyway:
#    datasources:
#        default:
#            enabled: true
#
#jpa:
#    default:
#        properties:
#            hibernate:
#                hbm2ddl:
#                    auto: update
#                show_sql: true
#datasources:
#    default:
#        url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
#        driver-class-name: ${JDBC_DRIVER:org.h2.Driver}
#        username: ${JDBC_USER:sa}
#        password: ${JDBC_PASSWORD:"password"}
#
#h2:
#    console:
#        enabled:true
#
#jpa:
#    default:
#        properties:
#            hibernate:
#                hbm2ddl:
#                    auto: update
#                show_sql: true
#flyway:
#    datasources:
#        default:
#            enabled: true