datasources:
    default:
        dialect: H2
        driverClassName: org.h2.Driver
        password: ''
        schema-generate: CREATE_DROP
        url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
        username: sa
jpa:
    default:
        properties:
            hibernate:
                hbm2ddl:
                    auto: update
micronaut:
    application:
        name: micronautH2
